export const food_menu_item = [
  {
    image: "BabyCorn_Ghee_Roast.jpg",
    productName: "BabyCorn Ghee Roast",
    description:
      "A Spicy and Popular Dish usually found in the Coastal Regions of Karnataka, India. Baby Corn cooked in a Gravy made of Dry Roasted Spices and garlic blend into a smooth paste.",
    price: 10,
    isDeleted: false,
    category: "Main Course",
    cuisine: "Indian",
    preference: "Vegetarian",
    stockQuantity: 10,
  },
  {
    image: "Scotch_Eggs.jpg",
    productName: "Scotch Eggs",
    description:
      "A traditional British Dish containg a Hard-Boiled Egg wrapped in Meat(Chicken/Pork) and covered in breadcrumbs to be fried/baked.",
    price: "15",
    isDeleted: false,
    category: "Main Course",
    cuisine: "British",
    preference: "Non-Vegetarian",
    stockQuantity: 150,
  },
  {
    image: "Denver_Omelet.jpg",
    productName: "Denver Omelet",
    description:
      "Classic Diner Order served with a side of Hash Browns or Toast. Has a firmer texture and a more caramelized flavor compared to a classic French Omelet ",
    price: "20",
    isDeleted: false,
    category: "Appetizer",
    cuisine: "American",
    preference: "Non-Vegetarian",
    stockQuantity: 125,
  },
  {
    image: "Vanilla_Panna_Cotta.jpg",
    productName: "Vanilla Panna Cotta with Chocolate Sauce",
    description:
      "A 'chilled' Italian Dessert. Silky Smooth Eggless Custard that literally means Cooked Cream. Served with a Drizzle of Chocolate Syrup.",
    price: "23",
    isDeleted: false,
    category: "Dessert",
    cuisine: "Italian",
    preference: "Vegetarian",
    stockQuantity: 100,
  },
  {
    image: "Chicken_Schnitzel.jpg",
    productName: "Chicken Schnitzel",
    description:
      "Traditional German Dish. Pounded Meat(Chicken) coated with Egg Wash and Breadcrumbs mixed with Seasonings",
    price: "30",
    isDeleted: false,
    category: "Main Course",
    cuisine: "German",
    preference: "Non-Vegetarian",
    stockQuantity: 120,
  },
  {
    image: "Palak_Paneer.jpg",
    productName: "Palak Paneer",
    description:
      "Classical North Indian Dish made with succulent Cottage Cheese Cubes cooked in a Smooth Spinach Gravy",
    price: "30",
    isDeleted: false,
    category: "Main Course",
    cuisine: "Indian",
    preference: "Vegetarian",
    stockQuantity: 120,
  },
  {
    image: "Turkish_Poached_Eggs.jpg",
    productName: "Turkish Poached Eggs (Cilbir)",
    description:
      "Traditional Mediterranean Dish. Perfectly Poached Eggs served over a Garlicky Yogurt, and finished with a warm Spicy Butter or Olive Oil",
    price: "30",
    isDeleted: false,
    category: "Main Course",
    cuisine: "Mediterranean",
    preference: "Non-Vegetarian",
    stockQuantity: 120,
  },
  {
    image: "Omurice.jpg",
    productName: "Omurice",
    description:
      "Contemporary Japanese Fusion Creation blending the Western Omelet and Japanese Fried Rice",
    price: "30",
    isDeleted: false,
    category: "Main Course",
    cuisine: "Japanese",
    preference: "Non-Vegetarian",
    stockQuantity: 120,
  },
  {
    image: "Paneer_Tikka.jpg",
    productName: "Paneer Tikka",
    description:
      "Popular Tandoor Based Snack. Marinated in a Spiced Yogurt, kept on Skewers and Grilled in an Oven.",
    price: "18",
    isDeleted: false,
    category: "Appetizer",
    cuisine: "Indian",
    preference: "Vegetarian",
    stockQuantity: 110,
  },
  {
    image: "Vanilla_Banana_Parfait.jpg",
    productName: "Vanilla Banana Parfait",
    description:
      "Parfait meaning Perfect - Dessert with Multiple Textures - Smooth from the Parfait, Crumbly from the Crackers and Wafers and Fruity from the Bananas.",
    price: "15",
    isDeleted: false,
    category: "Dessert",
    cuisine: "French",
    preference: "Vegetarian",
    stockQuantity: 200,
  },
  {
    image: "Creamy_Mushroom_Pasta.jpg",
    productName: "Creamy Mushroom Pasta",
    description:
      "A classic Italian Dish. Creamy flavor from the sauce and Umami Flavor from the Mushrooms gives the Perfect Harmony in your Mouth",
    price: "22",
    isDeleted: false,
    category: "Main Course",
    cuisine: "Italian",
    preference: "Vegetarian",
    stockQuantity: 130,
  },
  {
    image: "Custard_T_Cup.jpg",
    productName: "Custard T-Cup",
    description: "Modern take on Ice Cream and Custard. Served in a Tea Cup",
    price: "12",
    isDeleted: false,
    category: "Dessert",
    cuisine: "Modern",
    preference: "Vegetarian",
    stockQuantity: 100,
  },
  {
    image: "Vegetable_Pizza.jpg",
    productName: "Veggie Farmhouse Pizza",
    description:
      "A Simple many Veggies Pizza on a Medium Sized Soft Garlic flavored Crust.",
    price: "25",
    isDeleted: false,
    category: "Main Course",
    cuisine: "Italian",
    preference: "Vegetarian",
    stockQuantity: 100,
  },
];

export const drinks_menu_item = [
  {
    image: "Hefeweizen.jpg",
    productName: "Hefeweizen",
    description: "German Style, Pale Yellow, Wheat Beer with heat of Banana",
    price: "10",
    isDeleted: false,
    category: "Beer",
    level: "5.2",
    stockQuantity: 100,
  },
  {
    image: "Whiskey_Sour.jpg",
    productName: "Whiskey Sour",
    description:
      "A Cocktail containing whiskey (often bourbon), lemon juice, sugar, and optionally, a dash of egg white or cocktails foamer.",
    price: "15",
    isDeleted: false,
    category: "Cocktail",
    level: "14",
    stockQuantity: 150,
  },
  {
    image: "Long_Island_Iced_Tea.jpg",
    productName: "Long Island Iced Tea",
    description:
      "A Cocktail containing Vodka, Tequila, Light Rum, Triple Sec, Gin, and a Splash of Cola - Giving it a final amber hue of an Iced Tea.",
    price: "20",
    isDeleted: false,
    category: "Cocktail",
    level: "22",
    stockQuantity: 125,
  },
  {
    image: "Sauvignon_Blanc.jpg",
    productName: "Sauvignon Blanc White Wine",
    description:
      "A White Wine Grape variety that is most often used to Produce Dry White Wines. Light and Refreshing, has a Great Minerality, Aromas and Tastes of Herbs and Grasses.",
    price: "23",
    isDeleted: false,
    category: "Wine",
    level: "14.5",
    stockQuantity: 100,
  },
  {
    image: "Merlot.jpg",
    productName: "Fratelli Merlot",
    description:
      "Vibrant Ruby Coloured Wine with a Deep Robe. Distinct Aromas of Plum and Dark Chocolate with Slightly Earthy Undertones Characterize this Wine",
    price: "30",
    isDeleted: false,
    category: "Wine",
    level: "12",
    stockQuantity: 120,
  },
  {
    image: "American_Amber_Ale.jpg",
    productName: "American Amber Ale",
    description:
      "An Amber, Hoppy, Moderate-Strength American Craft Beer with a Caramel Malty Flavor.",
    price: "30",
    isDeleted: true,
    category: "Beer",
    level: "6.2",
    stockQuantity: 120,
  },
  {
    image: "Margarita.jpg",
    productName: "Margarita",
    description:
      " A Cocktail consisting of Tequila, Orange Liqueur, and Lime Juice often served with Salt on the Rim of the Glass.",
    price: "30",
    isDeleted: false,
    category: "Cocktail",
    level: "33",
    stockQuantity: 120,
  },
  {
    image: "Bloody_Mary.jpg",
    productName: "Bloody Mary",
    description:
      "A Cocktail containing Vodka, Tomato Juice, Worcestershire Sauce, Black Pepper, Celery Salt, Tabasco and Lemon Juice.",
    price: "30",
    isDeleted: false,
    category: "Cocktail",
    level: "9",
    stockQuantity: 120,
  },
  {
    image: "Stout_Beer.jpg",
    productName: "Stout Beer",
    description:
      "A Dark Beer made using Roasted Malt or Roasted Barley, Hops, Water and Yeast.",
    price: "18",
    isDeleted: false,
    category: "Beer",
    level: "5",
    stockQuantity: 110,
  },
  {
    image: "Virgin_Mojito.jpg",
    productName: "Virgin Mojito",
    description:
      "Non-Alcoholic Drink - Complex and Refreshing Blend of Mint, Citrus, and Sugar. This Drink is Guaranteed to Cut through the Summer Heat. ",
    price: "15",
    isDeleted: false,
    category: "Mocktail",
    level: "0",
    stockQuantity: 200,
  },
  {
    image: "Red_Wine_Sangria.jpg",
    productName: "Red Wine Sangria",
    description:
      "A traditional Beverage originating from Spain, Red Wine Sangria is a Sweet Cocktail prepared using Red Wine, Fresh Fruits, Soda, and Liqueur",
    price: "22",
    isDeleted: false,
    category: "Cocktail",
    level: "10",
    stockQuantity: 130,
  },
  {
    image: "Virgin_Pina_Colada.jpg",
    productName: "Virgin Pina Colada",
    description:
      "Non-Alcoholic Drink - Refreshing - Made with Pineapple Juice and Coconut Milk along with some Ice Cubes.",
    price: "25",
    isDeleted: false,
    category: "Mocktail",
    level: "0",
    stockQuantity: 100,
  },
];
